### ISSUE TITLE
Can't enter ROM

### ISSUE THREAD

**Issue by kpovisils** [Lorenzooone/MOTHER-3-Randomizer#6]
When I enter the ROM I typed in, the .exe closes and nothing seems to happen. Am I doing something wrong or is this an issue? I'm on Windows 10.

**Comment by Lorenzooone** [comment]
It should have randomized your ROM.
Is that not the case?

(It's normal that it doesn't say anything after that)

**Comment by kpovisils** [comment]
I used the fan translation. Is that something I can use?

**Comment by Lorenzooone** [comment]
Yes, it works with all versions. Have you tried facing some enemies? Are they the same?

**Comment by kpovisils** [comment]
It works! Proof:
![mGBA - MOTHER3 (59 9 fps) - 0 8 3 11_25_2021 8_22_20 AM](https://user-images.githubusercontent.com/94987638/143449372-11b7091e-b12e-40be-9e0e-8ed8e5e790ec.png)
